version: "3.8"

services:
  u22_ros2_humble:
    container_name: u22_ros2_humble_cnt
    build: .
    image: ubicoders/u22_ros2_humble:latest
    network_mode: host
    privileged: true
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1 
    volumes:
      - "/tmp/.X11-unix/:/tmp/.X11-unix/:rw"
      - "$HOME/.Xauthority:/root/.Xauthority:rw"
      - "/dev/:/dev/"
    # entrypoint: /bin/bash
    # deploy:
    #   resources:
    #       reservations:
    #           devices:
    #           - driver: nvidia
    #             count: all
    #             capabilities: [gpu, compute, utility, graphics, compat32, video, display]

